//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterProject_WPF_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.orderTable = new HashSet<orderTable>();
        }
    
        public int customer_id { get; set; }
        public string customer_name { get; set; }
        public string customer_surename { get; set; }
        public int customer_address_id { get; set; }
        public int customer_phone { get; set; }
        public string customer_email { get; set; }
        public string customer_nip { get; set; }
    
        public virtual addressTable addressTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderTable> orderTable { get; set; }
    }
}
