//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterProject_WPF_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<addressTable> addressTable { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<delivery_type> delivery_type { get; set; }
        public virtual DbSet<orderTable> orderTable { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<worker> worker { get; set; }
    }
}
